import {
  fireEvent,
  render,
  screen,
  waitFor,
} from "@testing-library/react-native";
import { router } from "expo-router";
import React from "react";
import NameScreen from "@/app/(app)/(payment)/name";
import { useThemeColors } from "@/hooks/use-theme-colors";
import { usePaymentStore } from "@/store/paymentStore";

// Mock expo-router
jest.mock("expo-router", () => ({
  router: {
    push: jest.fn(),
  },
}));

// Mock hooks
jest.mock("@/hooks/use-theme-colors", () => ({
  useThemeColors: jest.fn(),
}));

// Mock Zustand store
jest.mock("@/store/paymentStore", () => ({
  usePaymentStore: jest.fn(),
}));

describe("NameScreen", () => {
  const mockSetName = jest.fn();
  const mockLogMMKV_Zustand = jest.fn();
  const mockName = "";

  const mockColors = {
    background: "#FFFFFF",
    text: "#000000",
    buttonBackground: "#007AFF",
    buttonText: "#FFFFFF",
    border: "#E0E0E0",
    icon: "#999999",
    error: "#FF0000",
    errorBackground: "#FFF5F5",
    screenBackground: "#F5F5F5",
    textSecondary: "#666666",
  };

  beforeEach(() => {
    jest.clearAllMocks();
    (useThemeColors as jest.Mock).mockReturnValue(mockColors);
    (usePaymentStore as unknown as jest.Mock).mockReturnValue({
      name: mockName,
      setName: mockSetName,
      logMMKV_Zustand: mockLogMMKV_Zustand,
    });
  });

  // Test 1: Invalid name shows error message
  it("should display error message when name is invalid (less than 3 characters)", async () => {
    render(<NameScreen />);

    const nameInput = screen.getByPlaceholderText("Name");

    // Enter invalid name (too short)
    fireEvent.changeText(nameInput, "Jo");

    // Wait for validation
    await waitFor(() => {
      expect(screen.getByText("Name must be at least 3 letters")).toBeTruthy();
    });
  });

  // Test 2: Invalid name with non-alphabetic characters shows error
  it("should display error message when name contains non-alphabetic characters", async () => {
    render(<NameScreen />);

    const nameInput = screen.getByPlaceholderText("Name");

    // Enter invalid name (contains numbers)
    fireEvent.changeText(nameInput, "John123");

    // Wait for validation
    await waitFor(() => {
      expect(screen.getByText("Name must be at least 3 letters")).toBeTruthy();
    });
  });

  // Test 3: Continue button is disabled when name is invalid
  it("should disable Continue button when name is invalid", async () => {
    render(<NameScreen />);

    const nameInput = screen.getByPlaceholderText("Name");
    const continueButton = screen.getByText(/continue/i);

    // Enter invalid name
    fireEvent.changeText(nameInput, "Jo");

    // Wait for validation
    await waitFor(() => {
      expect(screen.getByText("Name must be at least 3 letters")).toBeTruthy();
    });

    // Get the parent TouchableOpacity to check disabled state
    const touchableOpacity = continueButton.parent?.parent;
    const isDisabled =
      touchableOpacity?.props?.disabled ||
      touchableOpacity?.props?.accessibilityState?.disabled;

    // Button should be disabled
    expect(isDisabled).toBeTruthy();

    // Try to press it - should not navigate
    fireEvent.press(continueButton);
    expect(router.push).not.toHaveBeenCalled();
    expect(mockSetName).not.toHaveBeenCalled();
  });

  // Test 4: Valid name enables Continue button and navigates/stores name
  it("should enable Continue button, store name, and navigate when name is valid", async () => {
    render(<NameScreen />);

    const nameInput = screen.getByPlaceholderText("Name");
    const continueButton = screen.getByText(/continue/i);
    const validName = "John Doe";

    // Enter valid name
    fireEvent.changeText(nameInput, validName);

    // Wait for validation to pass
    await waitFor(() => {
      expect(screen.queryByText("Name must be at least 3 letters")).toBeNull();
    });

    // Get the parent TouchableOpacity to check disabled state
    const touchableOpacity = continueButton.parent?.parent;
    const isDisabled =
      touchableOpacity?.props?.disabled ||
      touchableOpacity?.props?.accessibilityState?.disabled;

    // Button should be enabled
    expect(isDisabled).toBeFalsy();

    // Press Continue button
    fireEvent.press(continueButton);

    // Should save name to store (promo code will be generated by usePromoCode hook)
    expect(mockSetName).toHaveBeenCalledWith(validName);

    // Should log MMKV/Zustand
    expect(mockLogMMKV_Zustand).toHaveBeenCalled();

    // Should navigate to product screen
    expect(router.push).toHaveBeenCalledWith("./product");
  });

  // Test 5: Valid name with spaces should pass validation
  it("should accept valid name with spaces", async () => {
    render(<NameScreen />);

    const nameInput = screen.getByPlaceholderText("Name");
    const continueButton = screen.getByText(/continue/i);
    const validNameWithSpaces = "Mary Jane Watson";

    fireEvent.changeText(nameInput, validNameWithSpaces);

    // Wait for validation to pass
    await waitFor(() => {
      expect(screen.queryByText("Name must be at least 3 letters")).toBeNull();
    });

    // Button should be enabled
    const touchableOpacity = continueButton.parent?.parent;
    const isDisabled =
      touchableOpacity?.props?.disabled ||
      touchableOpacity?.props?.accessibilityState?.disabled;
    expect(isDisabled).toBeFalsy();
  });

  // Test 8: Empty name should not show error initially
  it("should not show error message when name input is empty", () => {
    render(<NameScreen />);

    const nameInput = screen.getByPlaceholderText("Name");

    // Input should be empty initially
    expect(nameInput.props.value).toBe("");

    // Should not show error message
    expect(screen.queryByText("Name must be at least 3 letters")).toBeNull();
  });
});
